# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
# bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, A, Claude, exec, omarchy-launch-webapp "https://claude.ai"
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-or-focus-webapp Calendar "https://calendar.google.com/calendar/u/0/r"
bindd = SUPER SHIFT, W, Gmail, exec, omarchy-launch-webapp "https://mail.google.com/mail/u/0/"
bindd = SUPER SHIFT, E, Gmail, exec, omarchy-launch-webapp "https://mail.google.com/mail/u/1/"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT, S, Slack, exec, omarchy-launch-or-focus-webapp Slack "https://app.slack.com/client/T03750LEA/GGZFYDGRE"
bindd = SUPER SHIFT, R, Screenshot, exec, omarchy-cmd-screenshot smart clipboard
# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
bindd = SUPER SHIFT, J, Calendarchy, exec, omarchy-launch-tui calendarchy

# Toggle keyboard layout (Alt+Space)
bindd = ALT, SPACE, Toggle keyboard layout, exec, hyprctl switchxkblayout all next
