# See bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus signal "uwsm-app -- signal-desktop"
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
# env = GDK_SCALE,2
# monitor=,3840x2160@120,auto,auto
#

# Good compromise for 27" or 32" 4K monitors (but fractional!)
env = GDK_SCALE,1.75
monitor = desc:Dell Inc. DELL U3225QE, 3840x2160@120, auto, 1.6


# Straight 1x setup for low-resolution displays like 1080p or 1440p
# env = GDK_SCALE,1
# monitor=,preferred,auto,1

